service:
  name: ${pipelineName}
  identifier: ${pipelineIdentifier}
  orgIdentifier: ${orgIdentifier}
  projectIdentifier: ${projectIdentifier}
  serviceDefinition:
    type: Kubernetes
    spec:
      manifests:
        - manifest:
            identifier: INT
            type: HelmChart
            spec:
              store:
                type: Github
                spec:
                  connectorRef: account.Github
                  gitFetchType: Branch
                  repoName: helm-chart-${projectName}
                  folderPath: /helm-charts-${projectName}
                  branch: main
              valuesPaths:
                - manifests/${pipelineName}/sit/immutable/values.yaml
              subChartPath: ""
              skipResourceVersioning: true
              enableDeclarativeRollback: false
              helmVersion: V3
              fetchHelmChartMetadata: false
