service:
  name: ${pipelineName}
  identifier: ${pipelineIdentifier}
  orgIdentifier: ${orgIdentifier}
  projectIdentifier: ${projectIdentifier}
  serviceDefinition:
    spec:
      manifests:
        - manifest:
            identifier: INT
            type: HelmChart
            spec:
              store:
                type: Github
                spec:
                  connectorRef: account.Github
                  gitFetchType: Branch
                  folderPath: "/helm-charts"
                  repoName: helm-chart-harness
                  branch: main
              subChartPath: ""
              valuesPaths:
              #- manifests/${repoName}/sit/configmap/configmap.yaml
              - manifests/${repoName}/sit/immutable/values.yaml
              - trigger-values/<+pipeline.triggerType>/values.yaml              
              skipResourceVersioning: false
              enableDeclarativeRollback: false
              helmVersion: V3
              fetchHelmChartMetadata: false
    type: Kubernetes
